# This is a basic workflow to help you get started with MATLAB Actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events, but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PRODUCT_LIST: MATLAB MATLAB_Test SimBiology Statistics_and_Machine_Learning_Toolbox 

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only allow one build of this type to run at a time
# Ensure results publishing completes without being interrupted/overwritten
concurrency:
  group: "test"
  cancel-in-progress: false

jobs:

  test:

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Check out your repository
      - uses: actions/checkout@v5
      
      # Set up MATLAB on a GitHub-hosted runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: ${{ env.PRODUCT_LIST }}
          cache: true

      # Run the MATLAB build tool to build and test your code
      - name: Run buildtool
        uses: matlab-actions/run-build@v2
        with:
          tasks: test
